#!/usr/bin/env php
<?php

// Ensure CLI usage
if (PHP_SAPI !== 'cli') {
    exit('This script can only be run from the command line.');
}

// Basic command line interface
// echo "Welcome to Abhijaan Framework CLI Tool\n";
// echo "----------------------------------------\n\n";

// Check command-line arguments
if ($argc < 2) {
    help(); // Display help if no command is provided
} else {
    $command = $argv[1];

    switch ($command) {
        case "help":
            help();
            break;
        case "version":
            version();
            break;
        case "run":
            run();
            break;
        default:
            help();
    }
}


// Run function
function run() {
    echo "Running your project at localhost:2323\n";
    exec("php -S localhost:2323 -t .");
}

// uses function
function help() {
    cli_logo();
    echo "\033[33musage:\033[32m php fuel\033[0m <--command-->\n\n";
    echo "\033[33mcommands:\033[0m\n";
    echo "\t\033[32mrun:\033[0m\t\trun your project at localhost (default port:2323)\n";
    echo "\t\033[32mhelp:\033[0m\t\thelp\n";
    echo "\t\033[32mversion:\033[0m\tversion\n";
    exit(1);
}

// version function
function version() {
    cli_logo();
    exit(1);
}


                                                                                

                                                                                



                                                                                
function cli_logo() {
    echo " \t\t\t\t\t    \033[1m\033[44m </> \033[0m\033[37m\033[1m";
    echo "\033[36m
╔───────────────────────────────────────────────╗ 
│    ___   ___  __ ______   _____   ___   _  __ │ 
│   / _ | / _ )/ // /  _/_ / / _ | / _ | / |/ / │ 
│  / __ |/ _  / _  // // // / __ |/ __ |/    /  │ 
│ /_/ |_/____/_//_/___/\___/_/ |_/_/ |_/_/|_/   │ 
╚───────────────────────────────────────────────╝ \n";
    echo "\033[0m\033[31m\033[6mABHIJAAN\033[0m Framework version \033[32m0.1.0\033[0m 2024\n\n";
}
                           